name: Sync Public Folder

on:
  schedule:
    - cron: '0 7 * * *'  # 1 AM Central Time (7 AM UTC)
  workflow_dispatch:

jobs:
  sync-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Personal Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Sparse Checkout
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git init

          # Check if remote exists, and only add if it doesn't
          if ! git remote get-url origin; then
            git remote add origin https://github.com/vz-risk/VCDB.git
          fi

          # Enable sparse-checkout
          git sparse-checkout init --cone
          git sparse-checkout set data/json

          # Pull from the 'main' branch (not 'master')
          git pull origin main

          # List the files in the repo to debug
          echo "Listing files after sparse-checkout:"
          ls -R

          # Check if the 'data/json' folder exists
          if [ ! -d "data/json" ]; then
            echo "data/json folder not found!"
            exit 1
          fi

          # Optional: clean old copy of data/json
          rm -rf data/json

          # Copy the sparse-checkout folder directly to your local data folder
          cp -r data/json ./data/

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Auto-sync data/json from VCDB" || echo "No changes"
          git push
