name: Sync Public Folder

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 3am UTC
  workflow_dispatch:

jobs:
  sync-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Personal Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull data from VCDB Repository
        run: |
          # Clone the public VCDB repository into a temporary directory
          git clone --single-branch --branch master https://github.com/vz-risk/VCDB.git temp_repo

          # Copy the 'data/json' folder from VCDB into the 'data/json' folder of your repo
          cp -r temp_repo/data/json ./data/

          # Clean up the temporary repository
          rm -rf temp_repo

      - name: Commit and Push Changes
        run: |
          git add data/json
          git commit -m "Auto-sync data/json from VCDB" || echo "No changes"
          git push
