name: Sync Public Folder

on:
  schedule:
    - cron: '0 7 * * *'  # 1 AM Central Time (7 AM UTC)
  workflow_dispatch:

jobs:
  sync-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Personal Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Sparse Checkout
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git init
          git remote add origin https://github.com/vz-risk/VCDB.git

          # Enable sparse-checkout
          git sparse-checkout init --cone
          git sparse-checkout set data/json
          git pull origin master

          # Optional: clean old copy of data/json
          rm -rf data/json

          # Copy the sparse-checkout folder directly to your local data folder
          cp -r data/json ./data/

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Auto-sync data/json from VCDB" || echo "No changes"
          git push
